language: php

php: [7, 7.1]

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update && composer install --optimize-autoloader --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)